machine:
  environment:
    PATH: $HOME/.asdf/bin:$HOME/.asdf/shims:$PATH

dependencies:
  cache_directories:
    - ~/.asdf
  override:
    - git clone https://github.com/HashNuke/asdf.git ~/.asdf || `:`
    - asdf plugin-add erlang https://github.com/HashNuke/asdf-erlang.git || `:`
    - asdf plugin-add elixir https://github.com/HashNuke/asdf-elixir.git || `:`
    - asdf install erlang '20.0'
    - asdf install elixir '1.6.4'
    - asdf global erlang '20.0'
    - asdf global elixir '1.6.4'
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix deps.compile

test:
  override:
    - mix test

deployment:
  production:
    branch: master
    commands:
      - mix edeliver build release
      - mix edeliver deploy release to production
      - mix edeliver restart production
      - mix edeliver migrate production